### ISSUE TITLE
Security Definitions

### ISSUE THREAD

**Issue by JoniSykes** [Surnet/swagger-jsdoc#141]
Hi,

I'm having trouble adding security definitions to my swagger jsdoc.

I'm using a global tag, but I've tried tagging specific operations as well, with no luck on either. 
The authorisations section in swagger-ui just stays empty.

I have tried basic auth as well, seeing as there are more examples of this online, no luck with that too. 

I'm using:
```
    "swagger-ui-express": "4.0.1",
    "swagger-jsdoc": "3.2.3",
```

Here's the config:
```
const swaggerDefinition = {
    info: {
        title: "Example API",
        version: "1.0.0",
        description: "A description",
    },
    host: "localhost:3000"
};
const options = {
    swaggerDefinition: swaggerDefinition,
    apis: ["./src/routes/*.js"],
    securityDefinitions: {
        Bearer: {
            type: "apiKey",
            name: "Authorization",
            in: "header"
        }
    },
    security: [
        {
            Bearer: []
        }
    ]
};
```

Thanks

**Comment by benfavre** [comment]
What I don't get is how on earth we have managed to get to Open API 3.0 and we still haven't got one single example on the entire internet on how to use a JWT token without a shitty request interceptor

**Comment by JoniSykes** [comment]
FWIW I've also tried using OpenAPI 3 syntax to no avail.

E.g:
```
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

**Comment by kalinchernev** [comment]
@JoniSykes @benfavre as I don't have your source code and use case, it's hard for me to guess what could be the reason for your results.

Have you seen this [tutorial](https://swagger.io/docs/specification/authentication/bearer-authentication/) or [this](https://swagger.io/docs/specification/authentication/)? Have you tried? What are your results?

**Comment by JoniSykes** [comment]
@kalinchernev Yes, I pasted my code above. 
I have tried interpreting the OpenAPI 3 version in my config, as well as using the better documented version 2 syntax (which is what I pasted above)
I have tried those docs already. 

The results are: Enabling globally for all operations shows an authentication button at the top of swagger-ui. Clicking opens an empty modal. 
Enabling per operation shows an auth button per operation configured, clicking it opens the same empty modal. 
Neither option is able to put any form of auth option inside the modal. 
I've tried adding basic auth (even though we don't need to) just to go back to basics and there's more docs/examples around for basic auth than JWT. Same results.

This leads me to think it's something to o with swagger-js, not swagger-ui-express.

**Comment by kalinchernev** [comment]
I'll try to reproduce the behavior when I have free time. It is possible that the issue comes from an [UI component](https://github.com/swagger-api/swagger-ui/search?q=auth&state=open&type=Issues) or some middleware (like [this](https://github.com/scottie1984/swagger-ui-express/issues/95)).

Best way to know whether it's an issue of swagger-jsdoc which is a parser of documentation comments or a swagger tool for specification visualization is to take your resulting specification from the swagger-jsdoc and paste it in swagger-ui or other specification validation tool. If there are no issues with the specification structure itself, then it means the UI part of the visualization of the operations most probably either does not handle the given component or there's a CORS/request/etc issue in the communication layer.

**Comment by JoniSykes** [comment]
@kalinchernev Thanks for the response and info. 

Interesting to see those linked issues. Might be related, as you say. 

I'll keep digging, thanks.

**Comment by benfavre** [comment]
The issue is with swagger-ui, not recognising type "http".
"The solution" is to use a custom request interceptor to prepend"Bearer: " in front of an API key.
```
type: api_key
in: header
name: Authorization
```

**Comment by JoniSykes** [comment]
@benfavre Thanks for your contribution. This is actually the first thing I tried. See my original config.

**Comment by kalinchernev** [comment]
Hi all, I had an hour today to try and inspect the issue here.
What I did was to [read this article](https://swagger.io/docs/specification/authentication/), take [the first example which comes to mind](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml), [simplify it](https://gist.github.com/kalinchernev/c68f1dde5e8c146b14087352533caafd), test it in [online demo of swagger ui](https://petstore.swagger.io/) and I saw the tool provides windows for auth correctly:

![swagger ui - ok](https://user-images.githubusercontent.com/1923476/48981284-09a3c800-f0dc-11e8-8d49-000f16b93c33.png)

Next, I took the [existing example](https://github.com/Surnet/swagger-jsdoc/tree/master/example/v2) and made a separate project to focus on smaller scope, not the whole swagger-jsdoc repository. I placed [components in a separate yaml file](https://github.com/kalinchernev/demo-open-api-security-swagger-jsdoc/blob/master/components.yaml). I took these copy-pasting the [examples given earlier](https://swagger.io/docs/specification/authentication/#securitySchemes).

I kept the rest of the setup of the example [express app just as it is](https://github.com/kalinchernev/demo-open-api-security-swagger-jsdoc/blob/master/index.js) and removed comments. This resulted in this JSON:

```json
{
  "openapi": "3.0.0",
  "info": { "title": "Secured API", "version": "1.0.0" },
  "paths": {
    "/": {
      "get": {
        "operationId": "open",
        "summary": "Open",
        "responses": { "200": { "description": "200 response" } }
      }
    },
    "/v2": {
      "get": {
        "operationId": "secured",
        "summary": "Secured",
        "security": [{ "ApiKeyAuth": [] }],
        "responses": { "200": { "description": "200 response" } }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BasicAuth": { "type": "http", "scheme": "basic" },
      "BearerAuth": { "type": "http", "scheme": "bearer" },
      "ApiKeyAuth": { "type": "apiKey", "in": "header", "name": "X-API-Key" },
      "OpenID": {
        "type": "openIdConnect",
        "openIdConnectUrl":
          "https://example.com/.well-known/openid-configuration"
      },
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://example.com/oauth/authorize",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
              "read": "Grants read access",
              "write": "Grants write access",
              "admin": "Grants access to admin operations"
            }
          }
        }
      }
    }
  },
  "tags": []
}
```

I copied this and pasted it in the [online editor](https://editor.swagger.io/) and it shows auth windows correctly as well:

![swagger editor - ok](https://user-images.githubusercontent.com/1923476/48981354-f1807880-f0dc-11e8-8ec0-bcba8ac3510f.png)

This leads me to conclusion that the `swagger-jsdoc` does its job, as well as `swagger-editor` and `swagger-ui`. I pushed my testing project [here](https://github.com/kalinchernev/demo-open-api-security-swagger-jsdoc) and haven't implemented `swagger-ui-express` as so far the editor and UI look good.

Feel free to use this example project. If my time spent on reproducing the issue hasn't given the issue anticipated, re-open the issue and please use the example project to submit your concrete code and issue so that I can debug it.

Thank you.

**Comment by davidgarvie** [comment]
FYI I was able to get global security definitions working with the following configuration: 
```
{
  swaggerDefinition: {
    openapi: '3.0.1',
    info: {
      ...
    },
    basePath: '/',
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        }
      }
    },
    security: [{
      bearerAuth: []
    }]
  },
  apis: ['/some/path.js|yml'],
};
```

**Comment by stevenliatti** [comment]
FYI, I added the `openapi: '3.0.1'` specification in my `swaggerDefinition` and it worked, thanks @andaralex @kalinchernev and @davidgarvie.

**Comment by SeanningTatum** [comment]
After adding 3.0.1, body is now not being passed. Anyone experiencing the same issue?

![image](https://user-images.githubusercontent.com/26712061/97242817-d15d1500-182f-11eb-95e9-c3ff3a4d104d.png)

**Comment by Ettore495** [comment]
@SeanningTatum  make sure your swagger spec matches that of open api. 

`    /**
     * @openapi
     *
     * /login:
     *   post:
     *     description: logs a user in
     *     produces:
     *       - application/json
     *     requestBody:
     *         content:
     *             application/json:
     *              schema:
     *                  $ref: '#/definitions/LoginDTO'
     *     responses:
     *       200:
     *         description: users
     *         schema:
     *           $ref: '#/definitions/User'
     */`

**Comment by zshawk1982** [comment]
> After adding 3.0.1, body is now not being passed. Anyone experiencing the same issue?
> 
> ![image](https://user-images.githubusercontent.com/26712061/97242817-d15d1500-182f-11eb-95e9-c3ff3a4d104d.png)


look https://stackoverflow.com/questions/58634566/swagger-openapi-3-0-x-empty-body ，it can help you
