### ISSUE TITLE
change grouping and add version drop down

### ISSUE THREAD

**Issue by devkws** [Surnet/swagger-jsdoc#163]
Im looking to have swagger-ui look like our aspnetcore web api's swagger.

How would go about setting the route groups from "default" to "Twitter"
![image](https://user-images.githubusercontent.com/22294114/60112821-882e1a00-973e-11e9-8309-bc0668384f83.png)

and

how would I add a select a spec drop down? (image from aspnetcore web api)
![image](https://user-images.githubusercontent.com/22294114/60112854-98de9000-973e-11e9-8526-fdd6325f75f8.png)

**Comment by kalinchernev** [comment]
Hi @devkws Swagger UI is visualization tool for displaying swagger specifications. It's a separate project which is out of the scope of swagger-jsdoc.

You can find more about Swagger UI at:

- Official site: https://swagger.io/tools/swagger-ui/
- Configuration options: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

In order to tweak the UI, you either have to find the right option or modify the default build of the swagger ui project.

The issue queue where you can address the question if documentation does not help: https://github.com/swagger-api/swagger-ui/issues

**Comment by Jiunsr** [comment]
I had this problem too, and found the answer. Click on the link to find the configuration item swaggerOptions in the title "Load swagger from url" can be implemented.
https://www.npmjs.com/package/swagger-ui-express
