### ISSUE TITLE
Option to remove swagger 2.0 definition.

### ISSUE THREAD

**Issue by Subalee** [Surnet/swagger-jsdoc#203]
Hey, when I try to use editor.swagger.io (basically i use it as a validator for my open api spec that is generated via swagger-jsdoc) I get  an error that openapi: 3.x and swagger can't coexist.

Would it be possible to remove `swagger: 2.0` when `openapi: 3.x` is present or provide an option to explicitly do so?

**Comment by kalinchernev** [comment]
When you set `openapi` property to the definition, then the specification format is targeting v3 and basically the `components` is added. The `swagger` property is not added.

When you set `swagger` property to the definition, then the specification format is targeting v2. Neither the `openapi` property is not added, nor the `swagger` one.

If you, as an author of the definition, include both `openapi` and `swagger` properties, then the resulting specification will target v3. That's because v2 was the first spec to support, and it's the default one. Adding `openapi` was introduced with the openapi initiative and v3, i.e. way later. So it's the first `if` check.

Thus, my suggestion based on assumptions and lack of facts and sample files => remove the `openapi` if you want to target v2 and remove `swagger` if you want to target v3.
