### ISSUE TITLE
Maintainer announcement

### ISSUE THREAD

**Issue by kalinchernev** [Surnet/swagger-jsdoc#268]
Dear community,

With this message I officially give up on maintaining the project and express my position of unwillingness to further reply to questions or provide help in general. I've been trying to keep the project afloat in the last couple of years following up on the most important aspects such as openapi integration, support for yaml, test coverage and overall code quality. 

I've been doing my work for free, in my free time, with focus on providing decent code quality for anyone to be able to continue on after me. However, the reactions I've been getting have been demotivating to say the least and I've reconsidered investing my energy here.

The owner of the project is @chdanielmueller and he'll decide if and who would be having right access for the future.

**Comment by daniloab** [comment]
Hello, first thanks for the time dedicated to swagger-jsdoc and I'm sorry if what was returned was not what was expected.

In spite of everything, I think swagger-jsdoc is a fantastic library that has helped in many places over the years.

I would like to make myself available to become a maintainer of the lib and learn from you how best to continue with it.

I believe that this will help me a lot to evolve within my career and in other personal aspects.

**Comment by chdanielmueller** [comment]
Hi @kalinchernev,

I am sorry to hear that, but I do understand your decision.
Thank you for your dedicated work in this project over the last years.
You have certainly grown this project and maintained it very well.
I hope that despite your last experiences it was overall a good experience.

I wish you all the best in the future and hope our paths will cross again.

Thanks,
Daniel

**Comment by chdanielmueller** [comment]
Hi @daniloab,

I am glad to hear that you are interested in maintaining this project.
I would like to give you "Triage" access to the repository at first.
It allows you to manage issues and pull requests on the repo.
I think that would be a good start to getting familiar with the project.
I will be available for all the things that need more rights.
You can find my mail address on my GitHub Profile.
Is that okay for you?

After we built some trust I would like to give you "Write" access to the repo and as a final step give you access to npm which allows you to publish new versions yourself.
I am sure you understand that because of the size/reach of this image I will have to give you access in steps.

Another point I would like to address is that I would like more than one maintainer on this package.
This spreads the load across more people and allows for collaboration and second opinions.
**If you reading this would like to help out as well please write to this issue or write me a mail directly. (mail address is on my profile)**
There is no obligation to provide a certain amount of time.
It shall be used as a opportunity to learn and grow in the open source world.
Ohh and of course if interested I could add a donation link for people to support the maintainers of this package.

I am available for any questions anyone has.
Let's keep swagger-jsdoc going!

Thanks,
Daniel

**Comment by daniloab** [comment]
sure @chdanielmueller 

can we have a chat channel to speak with each one directly? For me, it's okay to start with what you thinking about it.

**Comment by chdanielmueller** [comment]
Sure I have opened a Slack Channel which could be open for anyone:
https://join.slack.com/t/slack-gln3366/shared_invite/zt-qlt08dur-coBeh8ZM11VbCZ6J3lzyNA

**Comment by chdanielmueller** [comment]
I opened a new issue with the topic to add new maintainers to the project: #273

Thanks again @kalinchernev for your work!
It has been very much appreciated!
