### ISSUE TITLE
Can't require swagger-jsdoc

### ISSUE THREAD

**Issue by a-dams154** [Surnet/swagger-jsdoc#270]
showing **error must use import to load ES module** when I run the code 

error code : 'ERR_REQUIRE_ESM'

![image](https://user-images.githubusercontent.com/52209091/117490678-bdd3f900-af8c-11eb-911f-92f818bf9d56.png)

**Comment by a-dams154** [comment]
> showing **error must use import to load ES module** when I run the code
> 
> error code : 'ERR_REQUIRE_ESM'
> 
> ![image](https://user-images.githubusercontent.com/52209091/117490678-bdd3f900-af8c-11eb-911f-92f818bf9d56.png)

I solved the issue by downgrading swager-jsdoc to 6.0.1

**Comment by daniloab** [comment]
In release candidate versions, bugs may occur in relation to esm modules and others.

The npm version has been fixed so that the latest is 6.1.0 thus avoiding these issues.

As the author of the issue downgraded to the latest version, we will be closing this issue.

Let's keep your bug listed in issue #249 so we can track the issue.

Thanks.
