### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by wtfmynamefits** [Surnet/swagger-jsdoc#366]
**Describe the bug**
Getting following warning Critical dependency: the request of a dependency is an expression

**To Reproduce**
Follow the tutorial on https://next-swagger-doc.productsway.com/ about generating swagger docs for Nextjs13:
[Usage #1: next-swagger-doc with Next.js 13](https://next-swagger-doc.productsway.com/#md:usage-1-next-swagger-doc-with-nextjs-13)

**Expected behavior**
No Warning

**Screenshots**
![image](https://github.com/Surnet/swagger-jsdoc/assets/77943431/91cb544f-983c-450c-ac2d-a45f21cde0e6)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 
**Additional context**
I followed the tutorial on https://next-swagger-doc.productsway.com/ about generating swagger docs for Nextjs13

**Comment by xHayden** [comment]
It's a problem with `const loadCjs = () => require(resolvedPath);` in `./node_modules/swagger-jsdoc/src/utils.js`.
I assume it's because webpack can't figure out what resolvedPath is to make a dependency graph.

After removing the Cjs loader from utils.js and clearing my .next cache, the error went away because the loader was never being used, but this is obviously not a final solution.

**Comment by veigajoao** [comment]
Any progress in this issue? Just had the exact same problem here

**Comment by rostwolke** [comment]
Exactly the same issue here. What @xHayden suggests works for me too.
