### ISSUE TITLE
definition? definitions?

### ISSUE THREAD

**Issue by Maples7** [Surnet/swagger-jsdoc#38]
In this package, [keyword `definition` is used](https://github.com/Surnet/swagger-jsdoc#re-using-model-definitions). However, in swagger spec 2.0, [`definitions` is used](https://github.com/OAI/OpenAPI-Specification/blob/master//versions/2.0.md#schema).

Any idea to comply to swagger spec 2.0? Or I've just missed some details? :open_mouth:

**Comment by kalinchernev** [comment]
Hi @Maples7 you have a good point here.
Currently, I've opened a pull for solving similar issue for tag vs tags #36
In this pull request I already include a deprecator function that will be used for some more properties, i.e definition vs definitions. Possibly there are more tags to be fixed in similar way.
Thanks for noticing and reporting, I could continue on the refactoring on these properties after the tag case is merged.

**Comment by Maples7** [comment]
@kalinchernev Okay, I see. Thanks for your explaining~

**Comment by kalinchernev** [comment]
Hi @Maples7 I just published a new version of the module, which should handle both singular and plural forms, together with updated examples. Could you please check if it's solving this issue?
Thanks

**Comment by Maples7** [comment]
@kalinchernev Great job! Working in version 1.8.1.

**Comment by kalinchernev** [comment]
@Maples7 thanks!
