### ISSUE TITLE
Using in typescript

### ISSUE THREAD

**Issue by KingWu** [Surnet/swagger-jsdoc#39]
Cannot install typings

typings install dt~swagger-jsdoc --global --save
typings ERR! message Unable to find "swagger-jsdoc" ("dt") in the registry.

**Comment by kalinchernev** [comment]
Hi @KingWu,

Being perfectly honest with you, first time I hear about typings. 
Though, I looked at this [readme file sources section](https://github.com/typings/typings#sources) and I think you could try npm instead of dt prefix to actually use the npm package registry.

Could you please check if you can use the npm in your toolchain?

**Comment by drGrove** [comment]
working on a PR to DT/DT

**Comment by drGrove** [comment]
Waiting on merge of DefinitelyTyped/DefinitelyTyped#11298
