### ISSUE TITLE
How to specify auth

### ISSUE THREAD

**Issue by otusweb** [Surnet/swagger-jsdoc#61]
I've created a node server and a documenting the API with swagger using swagger-jsdoc. I'm using Auth0 for authentication and would like to be able to tell swagger about it so it can pass the right information to the APIs.

How can I do that?

Swagger-node has a solution, but that is for swagger-node: https://github.com/swagger-api/swagger-node/issues/421

**Comment by kalinchernev** [comment]
I think you might be confusing the swagger documentation with your API.
What swagger node is doing is mapping controllers to routes for you to write code that matches the documentation.
If you're already created the node server, then the functionality is there and you only need to document it, not re-work it to be a middleware of a swagger plugin to work.
I think that what you need to do to document your authentication with swagger is have something [like this](https://github.com/LufthansaOpenAPI/Swagger/blob/master/LH_public_API_swagger_2_0.json#L18) which formats the information in a [certain way](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-6-defining-security/). However, I don't see a reason you may have to re-work an authentication endpoint just to glue to swagger.

**Comment by froston** [comment]
You can define it in swagger options:

```javascript
var options = {
  swaggerDefinition: {
    info: {
      title: 'Hello World', // Title (required)
      version: '1.0.0', // Version (required)
    },
  },
  apis: ['./routes.js'], // Path to the API docs
  securityDefinitions: {
    auth: {
      type: 'basic'
    }
  },
};

var swaggerSpec = swaggerJSDoc(options);
```

**Comment by alexey-sh** [comment]
@froston still nothing
<img width="788" alt="screen shot 2018-05-11 16 45 57" src="https://user-images.githubusercontent.com/1584156/39920944-d1b3dc9c-553a-11e8-87e7-ac7b3b7be44f.png">

**Comment by clarketm** [comment]
@alexey-sh

You need to provide **both** a * securityDefinitions* and a *security* property to the swagger options:
```js
var options = {
  swaggerDefinition: {
    info: {
      title: 'Hello World', // Title (required)
      version: '1.0.0', // Version (required)
    },
  },
  apis: ['./routes.js'], // Path to the API docs
  securityDefinitions: {
    auth: {
      type: 'basic'
    }
  },
  security: [
    { auth: [] }
  ]
};

var swaggerSpec = swaggerJSDoc(options);
```

**Comment by SinaniG1996** [comment]
Still nothing. What differences will be if i want to add Bearer auth?

**Comment by SinaniG1996** [comment]
Test comment

**Comment by clarketm** [comment]
@SinaniG1996 – for Bearer auth (in swagger 2.0) you would change `basic` to `apiKey`, add the `in: header` and prefix the value with `Bearer`:
```diff
...
  securityDefinitions: {
    auth: {
-      type: 'basic',
+      type: 'apiKey',
+      in: 'header'
    }
...
```

![image](https://user-images.githubusercontent.com/9957358/47202014-b1391800-d330-11e8-91c7-e3e8dc51023a.png)

**Comment by cptstffn** [comment]
Hi Guys, 

same error here. 
my sec definition is the same like above. no luck. any suggestions? 

securityDefinitions: {
    auth: {
      type: 'basic'
    }
  },
  security: [
    { auth: [] }
  ]

**Comment by andaralex** [comment]
I am also facing the same problem. Could anyone have an idea to add security definitions in swagger UI using this swagger-jsdoc node module.

**Comment by kalinchernev** [comment]
Hi all, I take note of the fact that a discussion on a closed issue keeps popping up regarding a topic which is also currently open in another issue: #141 

In order to receive efficient help from the community, please do also help others figure how they can help you guys. 

What I mean is:

- Use the active issues and pull requests which are open. The chance of getting effective feedback is higher as the more recent a topic (an issue/a pull request) is, the higher the chance the person working on that topic still remembers the issue and hopefully the solution.
- Give information about what exactly you have tried and what exactly didn't work. Saying "same error here" is vague. A link to anything concrete would help. Github provides [links to code](https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/), [links to comments](https://blog.github.com/changelog/2018-08-17-copy-url-comment-action/) and links to basically any other concepts which worth pointing out precisely to save time from misunderstandings.
- Provide samples of your code, which could be tried easily. Very few people, and me maintaining the project especially, have more than a few minutes to focus on an issue. If I can understand the problem and reproduce is for until 10 minutes, I will do my best to give guidelines/advice/solution or whatever necessary. If, on the other hand, I have to spend an hour or more, I'll queue the issue on a list of tasks which are usually handled every 3-6 months when I can tackle several issues at once in order to be more effective. 

In general, rarely anyone remembers or cares about an issue in a larger span of a few working days. If we help each other to be effective, issues will get solved more easily.

**Comment by shivanijaiswal123** [comment]
Try it out!!

var options = {
  swaggerDefinition: {
    info: {
      title: 'Hello World', // Title (required)
      version: '1.0.0', // Version (required)
    },
    securityDefinitions: {
      auth: {
        type: 'basic'
      }
    },
    security: [
      { auth: [] }
    ]
  },
  apis: ['./routes.js'], // Path to the API docs
};
