### ISSUE TITLE
[Maintainer] Maintenance questions

### ISSUE THREAD

**Issue by kalinchernev** [Surnet/swagger-jsdoc#76]
Hi @drGrove and @chdanielmueller,

There are few topics that I'd like to open for discussions. Your feedback is really welcome.

**1) Releases and change log**
Since the last 2 merge pull requests, I'm trying to maintain an automated change log with [standard version](https://github.com/conventional-changelog/standard-version). It's not perfect yet as it's necessary to include some sort of tagging of releases to make the explanations in the log more detailed. Yet, I am not able to push the small bumps in versions and change logs [since some time](https://github.com/Surnet/swagger-jsdoc/pull/73).

**2) ESLint**
I'd like to integrate this mainly because it's very flexible, has good community support for presets and is also well integrated with many IDEs. Here's a [comparison](https://www.sitepoint.com/comparison-javascript-linting-tools/) with pros and cons of other linting tools. The recently published [prettier](https://github.com/prettier/prettier) also integrates well with ESLint and Atom for example. This brings a really pleasant workflow.

**3) The Node version to support**
It's really honorable that the swagger-jsdoc module supports older versions of node. (not using ES2015 or newer language features) Though, the [LTS schedule](https://github.com/nodejs/LTS#lts-schedule1) shows that it's not really necessary anymore as things have changed after the merge with io.js 
I believe we can allow ourselves to use ES2015 features (like v4 or more) in the module safely enough at this point of time.
Similarly to ESLint adoption (with something like the [airbnb preset](https://www.npmjs.com/package/eslint-config-airbnb)) this change will bring better developer experience for the maintainers of the project.

**4) [Travis](https://travis-ci.org/) would be helpful having tests on several node versions**
It's similar to CircleCI with the [small and important difference](https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5) that we can run several types of tests.

Most of these are non-blocking questions for me, rather things to discuss in direction how to lift up the developer experience on the project. What are your views on these?

**Comment by drGrove** [comment]
I am definitely for moving to v4+. I think it's time that we move out of the node stone age.

ESLint is a great linter that I use in most of my other projects and think moving this project to use it would be great. Plus you can set tests to fail if lint fails ;)

I'm also a huge fan of Travis, but I think this is something for @chdanielmueller to decide.

**Comment by chdanielmueller** [comment]
Hi there,

**ESLint**
I totally agree to switch to ESLint as I replaced jscs also with ESLint in my private projects quite some time ago.

**Node Version**
As for node I would also recommend moving to v4 or higher.
We stayed on this version because of this issue: #16 
I think this applied to Ubuntu 14.04 which is now in Maintenance Update stage.
We would do the people using this systems a favor by "forcing" them to update their systems. 😃 

**Travis**
The reason I decided to go with CircleCI was their free enterprise plan which I use for my private repos.
It was less new things to learn when using one system for all repos. 😄 
I think your use case can be implemented with CircleCI 2.0 https://circleci.com/docs/2.0/workflows/
Can you please check if this would be an option? Otherwise I am totally fine with switching to TravisCI

Thanks,
Daniel
